service: registration-sns
app: dosen-telefon
org: dosentelefonde
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'SNS:Subscribe'
      Resource: "arn:aws:sns:eu-west-1:133355712185:dosen-telefon-registrations"

functions:
  sns-registrations:
    handler: handler.recieve
    events:
      - sns: arn:aws:sns:eu-west-1:133355712185:dosen-telefon-registrations
