org: gadmeer
app: dosentelefon
service: dosentelefon-user-service

frameworkVersion: ">=1.1.0 <2.0.0"


provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  logs:
    websocket: true
  iamManagedPolicies:
      - 'arn:aws:iam::411554656372:policy/DosenTelefonLambdaSES'
      - 'arn:aws:iam::411554656372:policy/executeAPIDosenTelefon'
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    CONNECT_TABLE: ${self:service}-connect-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CONNECT_TABLE}"

functions:
  create:
    handler: users/create.create
    events:
      - http:
          path: users
          method: post
          cors: true

  get:
    handler: users/get.get
    events:
      - http:
          path: users/{userId}
          method: get
          cors: true

  update:
    handler: users/update.update
    events:
      - http:
          path: users/{userId}
          method: put
          cors: true

  delete:
    handler: users/delete.delete
    events:
      - http:
          path: users/{userId}
          method: delete
          cors: true

  connectHandler:
    handler: lobby/connect.connectHandler
    events:
      - websocket:
          route: $connect
          cors: true
        #  authorizer: auth # references the auth function below

  disconnectHandler:
    handler: lobby/disconnect.disconnectHandler
    events:
      - websocket:
          route: $disconnect
          cors: true
  defaultHandler:
    handler: lobby/default.defaultHandler
    events:
      - websocket:
          route: $default
          cors: true
  auth:
    handler: lobby/auth.auth


resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: uuid
            AttributeType: S
        KeySchema:
          -
            AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    ConnectDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: connectId
            AttributeType: S
        KeySchema:
          -
            AttributeName: connectId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CONNECT_TABLE}
